### ISSUE TITLE
运营商问题

### ISSUE THREAD

**Issue by RubuJam** [blanboom/awesome-home-networking-cn#12]
「　移动宽带访问国外网站速度快，电信宽带国内线路质量较高，联通宽带则比较均衡　」
感觉不少地方移动都存在DNS污染的问题

**Comment by blanboom** [comment]
很多地方的移动宽带有 DNS 污染等各种奇奇怪怪的问题。不过有些地方的移动宽带，访问国外网站的速度还是又着不错的速度。
