### ISSUE TITLE
[Request] Discussion on the official website

### ISSUE THREAD

**Issue by RubuJam** [blanboom/awesome-home-networking-cn#16]
作者有考虑过利用`Material for MkDocs
`这类框架，部署官方网站吗？
但如果作者在中国大陆境内的话，合规性要求太高，感觉不太可能

**Comment by blanboom** [comment]
目前部署在 GitHub 上，感觉还是挺方便的。等以后内容更加丰富后，应该会考虑通过 GitHub Pages 搭建一个网站，方便阅读。
